name: Setup
runs:
  using: composite
  steps:
    - name: Setup MySQL
      shell: pwsh
      run: |
        # Force errors to be terminating so catch block is triggered
        $ErrorActionPreference = 'Stop'
        try {
          # Try installing MySQL from default choco
          choco install mysql -y --no-progress --params="/port:3306"
        } catch {
          Write-Host "Default MySQL installation failed (likely 403 from dev.mysql.com). Fallback to backup ZIP..."
          $backupUrl = "https://github.com/divinity76/php-src/releases/download/mysql-8.0.31-winx64.zip/mysql-8.0.31-winx64.zip"
          $destination = "C:\tools\mysql-8.0.31-winx64.zip"
          Invoke-WebRequest -Uri $backupUrl -OutFile $destination
          # 3) Expand the ZIP into C:\tools\mysql
          Expand-Archive -Path $destination -DestinationPath "C:\tools\mysql"
          # 4) Point to the MySQL bin directory in the environment PATH (for the current session)
          $mysqlDir = "C:\tools\mysql\mysql-8.0.31-winx64"
          $env:Path += ";$mysqlDir\bin"
          # 5) Initialize the MySQL data directory (insecure init => empty root password)
          & "$mysqlDir\bin\mysqld.exe" --initialize-insecure --datadir="$mysqlDir\data"
          # 6) Install MySQL as a Windows service named "MySQL80"
          & "$mysqlDir\bin\mysqld.exe" --install MySQL80 --datadir="$mysqlDir\data"
          # 7) Start the MySQL service
          Start-Service MySQL80
          # (Optional) Wait a few seconds to ensure MySQL is fully up:
          Start-Sleep -Seconds 2
        }
        mysql.exe --port=3306 --user=root --password="" -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'Password12!'; FLUSH PRIVILEGES;"
    - name: Setup MSSQL
      shell: pwsh
      run: |
        choco install sql-server-express -y --no-progress --install-arguments="/SECURITYMODE=SQL /SAPWD=Password12!"
    - name: Setup PostgreSQL
      shell: pwsh
      run: |
        Set-Service -Name "postgresql-x64-14" -StartupType manual -Status Running
        pwsh -Command { $env:PGPASSWORD="root"; & "$env:PGBIN\psql" -U postgres -c "ALTER USER postgres WITH PASSWORD 'Password12!';" }
